### ISSUE TITLE
Usage help: "lignin-dom bug: Invalid `CallbackRef` JsValue(1)"

### ISSUE THREAD

**Issue by platy** [Tamschi/lignin-dom#10] opened 2021-04-16 09:32 UTC
Hi,

I'm now trying event handlers and getting a bit stuck. First I had the "closure invoked recursively or destroyed already" error, that was because I dropped the `CallbackRegistration`. Now that I'm not dropping it, I'm getting "lignin-dom bug: Invalid `CallbackRef` JsValue(1)". I've only just got to grips with how to use `Pin` and I'm not confident with pin-projection yet so maybe I've done something wrong there. Or maybe I'm missing something in callback management.

If you've got any suggestions, that would be great, here are the bits of code I think are most relevant:

The event binding is created and the registration is stored in the `Model`:
https://github.com/platy/rust-fullstack-template/blob/ce91377a6c2b033dfa28767f7279c900562f702f/shared/src/lib.rs#L40-L49

The `Model` is pinned when created:
https://github.com/platy/rust-fullstack-template/blob/ce91377a6c2b033dfa28767f7279c900562f702f/web/src/lib.rs#L89-L91

The `Model` is stored pinned in the `Renderer`:
https://github.com/platy/rust-fullstack-template/blob/ce91377a6c2b033dfa28767f7279c900562f702f/web/src/lib.rs#L35

The render function passes the pinned model to the view:
https://github.com/platy/rust-fullstack-template/blob/ce91377a6c2b033dfa28767f7279c900562f702f/web/src/lib.rs#L58-L72

**Comment by Tamschi** [comment] 2021-04-16 09:54
That's clearly on me, that's why it says "lignin-dom bug".
This seems to be an issue with `lignin` though, rather, and more specifically with this function: <https://github.com/Tamschi/lignin/blob/develop/src/callback_registry.rs#L632-L653>

For some reason, the number isn't being recognised as valid non-zero integer.
I'll write a few Wasm/browser tests for that roundtrip and see what I can find.

**Comment by Tamschi** [comment] 2021-04-16 11:25
The simple round-trip through `JsValue` works fine at least when testing `lignin` in Firefox though.
Maybe something odd is happening due to the event handler. I'll add a test for that here.

Which browser does the error happen in and which browser version do you use?

**Comment by platy** [comment] 2021-04-16 12:12
That was using firefox, I get the same thing in chrome.

Here is the stacktrace from FF if that helps:

```
Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede<@http://[::1]:8080/app.js:318:19
logError/<@http://[::1]:8080/app.js:228:22
console_error_panic_hook::Error::new::hdd02f663c940575d@http://[::1]:8080/app_bg.wasm:wasm-function[2491]:0xd9501
console_error_panic_hook::hook_impl::hba73d7896aa9acf1@http://[::1]:8080/app_bg.wasm:wasm-function[290]:0x90312
console_error_panic_hook::hook::h18ad65e0b750503f@http://[::1]:8080/app_bg.wasm:wasm-function[2747]:0xdcebd
core::ops::function::Fn::call::h25b18b09d590d2df@http://[::1]:8080/app_bg.wasm:wasm-function[2282]:0xd617a
std::panicking::rust_panic_with_hook::h3e6619a8809a443a@http://[::1]:8080/app_bg.wasm:wasm-function[577]:0xa4f03
rust_begin_unwind@http://[::1]:8080/app_bg.wasm:wasm-function[2544]:0xda1be
std::panicking::begin_panic_fmt::h268cca988846a20c@http://[::1]:8080/app_bg.wasm:wasm-function[2942]:0xdf643
lignin_dom::diff::DomDiffer::new_for_element_child_nodes::{{closure}}::h334ea07ba053641f@http://[::1]:8080/app_bg.wasm:wasm-function[531]:0xa2478
<dyn core::ops::function::Fn<(A,B)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6fd998ff52faebf6@http://[::1]:8080/app_bg.wasm:wasm-function[532]:0xa2563
__wbg_adapter_20@http://[::1]:8080/app.js:246:10
real@http://[::1]:8080/app.js:211:20
EventListener.handleEvent*init/imports.wbg.__wbg_addEventListener_502683a26945b1a5<@http://[::1]:8080/app.js:523:25
handleError/<@http://[::1]:8080/app.js:258:22
web_sys::features::gen_EventTarget::EventTarget::add_event_listener_with_callback_and_add_event_listener_options::h0b7344b1a7ff0200@http://[::1]:8080/app_bg.wasm:wasm-function[330]:0x93dc2
lignin_dom::diff::DomDiffer::add_event_listener::h1f81f06a93d4d280@http://[::1]:8080/app_bg.wasm:wasm-function[76]:0x5ebe7
lignin_dom::diff::DomDiffer::update_element::h1a9f2d6c50d6b425@http://[::1]:8080/app_bg.wasm:wasm-function[70]:0x51f58
lignin_dom::diff::DomDiffer::diff_splice_node_list::h5f58ecf1cf2b3313@http://[::1]:8080/app_bg.wasm:wasm-function[67]:0x235e0
lignin_dom::diff::DomDiffer::diff_splice_node_list::h5f58ecf1cf2b3313@http://[::1]:8080/app_bg.wasm:wasm-function[67]:0x39638
lignin_dom::diff::DomDiffer::update_child_nodes::h5a5117dbde2c1db3@http://[::1]:8080/app_bg.wasm:wasm-function[71]:0x532b7
rust_fullstack_template_web::Renderer::render::h485c1f6ae5a42395@http://[::1]:8080/app_bg.wasm:wasm-function[165]:0x80d4a
rust_fullstack_template_web::start::h425335096d707899@http://[::1]:8080/app_bg.wasm:wasm-function[166]:0x8104d
start@http://[::1]:8080/app_bg.wasm:wasm-function[1913]:0xcf70c
init@http://[::1]:8080/app.js:607:10
async*@http://[::1]:8080/:8:9
```

**Comment by Tamschi** [comment] 2021-04-16 12:17
Thanks! I just managed to reproduce it, but it's very strange that it prints out `JsValue(1)`.

I'll dig a bit, hopefully it's just a typo somewhere.

**Comment by Tamschi** [comment] 2021-04-16 13:01
Nevermind, I found it 😑
Panic in eagerly evaluated error message. Just a moment.

**Comment by Tamschi** [comment] 2021-04-16 13:25
I don't know what I was thinking when I wrote this, but [it's fixed now](https://github.com/Tamschi/lignin-dom/commit/139157420503eb4aae507b94efbb553606bfa5dc).

You should be able to see your event handler in the performance tab too now, like this:
![image](https://user-images.githubusercontent.com/715360/115030435-5e238a00-9ec7-11eb-9d06-7b45991ce69c.png)

The tracing definitely slows it down a bit, slow tablet processor aside.
I'll have to add a note to the README on how to disable that for production.

**Closed as completed by Tamschi** 2021-04-16 13:25 UTC

**Comment by platy** [comment] 2021-04-16 15:08
Ok - I see it now. Thanks for the hint about the chrome performance tab too - I see it working now. Next is the DOM invalidation!

**Comment by Tamschi** [comment] 2021-04-16 15:59
> Ok - I see it now. Thanks for the hint about the chrome performance tab too - I see it working now. Next is the DOM invalidation!

I forgot to mention that this more concise trace only works if you forward the information, like this: <https://github.com/Tamschi/lignin-dom/blob/139157420503eb4aae507b94efbb553606bfa5dc/tests/web_event.rs#L17>

The [tracing](https://lib.rs/crates/tracing) crate is really nice for this use here, since it lets you easily log parameters and the default flame graph is considerably too verbose to be really useful.

**Comment by platy** [comment] 2021-04-21 08:46
Thanks for the tip - tracing is going to be really handy!
